package com.mycontacts.presentation.contact_operations.states

data class DeleteIconsVisibilityState(val isDeleteContactInfoPhotoIconVisible: Boolean, val isDeleteContactInfoLastNameIconVisible: Boolean)
